---
kind: "operation"
client: "atomist-bot"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.6"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "a0d2633"
  parameters:
    - "service": "berlin"
    - "path": "wood"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "AddLocalEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"
  parameters:
    - "editorName": "ChangeMemoryRequirements"
    - "description": "modify the memory level in deployments"
    - "groupId": "satellite-of-love"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "ChangeMemoryRequirements"
  group: "satellite-of-love"
  artifact: "atomist-k8-specs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/atomist-k8-specs"
    branch: "master"
    sha: "c23ed53"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170602144934"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "1.9.0"
  parameters:
    - "service": "toes"
    - "path": "toes"

