---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
editor:
  name: "AddLocalEditor"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.30.0-20170427011430"
  parameters:
    - "editorName": "RemoveService"
    - "description": "take a service out of deployment"
    - "groupId": "what"

---
kind: "operation"
client: "rug-cli 1.0.0-m.1"
editor:
  name: "RetireService"
  group: "satellite-of-love"
  artifact: "atomist-k8-specs"
  version: "1.0.0"
  origin:
    repo: "git@github.com:satellite-of-love/atomist-k8-specs"
    branch: "satellite-of-love"
    sha: "f8438dd"
  parameters:
    - "serviceName": "amsterdam"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170608065255"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "1.12.0"
  parameters:
    - "service": "lizardspit"
    - "path": "lizardspit"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170609011313"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "1.13.16"
  parameters:
    - "service": "giraffe"
    - "path": "giraffe"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170609011313"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "1.13.17"
  parameters:
    - "service": "shoeboll"
    - "path": "bollshoe"

