---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.3"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "738735a"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "ChangeMemoryRequirements"
  group: "satellite-of-love"
  artifact: "atomist-k8-specs"
  version: "0.1.1"
  origin:
    repo: "git@github.com:satellite-of-love/atomist-k8-specs"
    branch: "satellite-of-love"
    sha: "c3a4d60*"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "BumpVersion"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.3"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "738735a"
  parameters:
    - "component": "patch"

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.22"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "29e6449"
  parameters:
    - "service": "london"
    - "path": "london"

