---
kind: "operation"
client: "atomist-bot"
editor:
  name: "AddDeploymentSpec"
  group: "satellite-of-love"
  artifact: "new-project-rugs"
  version: "0.1.6"
  origin:
    repo: "git@github.com:satellite-of-love/new-project-rugs"
    branch: "master"
    sha: "a0d2633"
  parameters:
    - "service": "berlin"
    - "path": "wood"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "AddLocalEditor"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.25.0"
  origin:
    repo: "git@github.com:atomist-rugs/rug-editors.git"
    branch: "master"
    sha: "7557a1b"
  parameters:
    - "editorName": "ChangeMemoryRequirements"
    - "description": "modify the memory level in deployments"
    - "groupId": "satellite-of-love"

---
kind: "operation"
client: "rug-cli 0.30.2"
editor:
  name: "ChangeMemoryRequirements"
  group: "satellite-of-love"
  artifact: "atomist-k8-specs"
  version: "0.1.0"
  origin:
    repo: "git@github.com:satellite-of-love/atomist-k8-specs"
    branch: "master"
    sha: "c23ed53"

---
kind: "operation"
client: "atomist-bot"
editor:
  name: "AddRestEndpoint"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.12.5"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "master"
    sha: "89b8555"
  parameters:
    - "returnedClass": "Survey"
    - "fieldName": "seed"
    - "fieldType": "Int"
    - "repo": "atomist-k8-specs"
    - "handle": "{}"
    - "__mappedParameters": "{"0":{"localKey":"repo","foreignKey":"atomist://github/repository"}}"
    - "__parameters": "{"0":{"displayName":"Java return type","description":"type the endpoint will return","pattern":"@java_class","validInput":"Java class name like ThunderCougarFalconBird","minLength":1,"maxLength":100,"name":"returnedClass","decorated":true},"1":{"displayName":"pojo field name","description":"name of a field in your pojo, blank for none (or not a new pojo)","pattern":"@java_identifier","validInput":"Java identifier","minLength":1,"maxLength":100,"name":"fieldName","decorated":true},"2":{"displayName":"pojo field type","description":"type of that field in your pojo, blank for none (or not a new pojo)","pattern":"@any","validInput":"Java type","minLength":1,"maxLength":100,"name":"fieldType","decorated":true}}"
    - "__intent": "{"0":"add endpoint"}"
    - "__tags": "{"0":"satellite-of-love","1":"rest"}"
    - "__name": "AddRestEndpointPlease"
    - "__description": "run an editor to add a REST endpoint to this project"
    - "__kind": "command-handler"

