Feature: Tests from ChangeMemoryRequirements.rt
  This file was autogenerated.
  It aims to avoid collisions, not remove redundancy.
  You can probably consolidate a lot of the elements.




  Scenario: ChangeMemoryRequirements is added to your project by AddChangeMemoryRequirements
    Given the archive root
    When ChangeMemoryRequirements inputParameteristhe inputParameter value for ChangeMemoryRequirements is added to your project by AddChangeMemoryRequirements
    Then parameters were valid
    Then changes were made
    Then fileContains hello txt Hello Worldnot for ChangeMemoryRequirements is added to your project by AddChangeMemoryRequirements
